dataset:
  train:  # LMDB
    type: ChallengeDataset
    
    # for lmdb
    root: /public/rawvideo
    gt_folder: rgb/gt/
    lq_folder: Train/Train_yuv/
    
    # for dataset
    gt_path: Challenge_train_gt.lmdb
    lq_path: Challenge_train_lq.lmdb
    meta_info_fp: meta_info.txt
    gt_size: 128  # ground truth patch size: gt_size * gt_size
    use_flip: True
    use_rot: True  # rotation per 90 degrees
    random_reverse: False

    # for datasampler
    enlarge_ratio: 300  # enlarge dataset by randomly cropping.
    
    # for dataloader
    num_worker_per_gpu: 4  # 12 in total. mainly affect IO speed
    batch_size_per_gpu: 16  # bs=32, divided by 4 GPUs

  val:  # Disk IO
    type: VideoTestChallengeDataset
    #root: /media/x/Database/MFQEv2/
    gt_path: test_gt/
    lq_path: test_lq/
    #meta_info_fp: meta_info.txt
    #enlarge_ratio: 1
    #use_flip: False
    #use_rot: False
    #random_reverse: False

  test:
    type: VideoTestChallengeDataset
    gt_path: test_png/
    lq_path: test_png/

network:
  radius: 1  # total num of input frame = 2 * radius + 1

  stdf:
    in_nc: 3  # 1 for Y
    out_nc: 64
    nf: 32  # num of feature maps
    nb: 3  # num of conv layers
    base_ks: 3
    deform_ks: 3  # size of the deformable kernel
  
  qenet:
    in_nc: 64  # = out_nc of stdf
    out_nc: 3  # 1 for Y
    nf: 48
    nb: 4
    base_ks: 3

train:
  exp_name: Challange_R3_enlarge300x  # default: timestr. None: ~
  random_seed: 7
  pre-val: False  # evaluate criterion before training, e.g., ori PSNR
  num_iter: !!float 3000000
  interval_print: !!float 10
  interval_val: !!float 5000  # also save model
  pbar_len: 100
  reload: True
  checkpointfile: '/home/shik9/Public/1/PEN/exp/Challange_R3_enlarge300x/ckp_35000.pt'

  optim:
    type: Adam
    lr: !!float 1e-4  # init lr of scheduler
    betas: [0.9, 0.999]
    eps: !!float 1e-08

  scheduler:
    is_on: False
    type: CosineAnnealingRestartLR
    periods: [!!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4, !!float 5e+4]  # epoch interval
    restart_weights: [1, 0.5, 0.5, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  loss:
    type: CharbonnierLoss
    eps: !!float 1e-6

  criterion:
    type: PSNR
    unit: dB

test:
  restore_iter: !!float 300000
  pbar_len: 100
  restore_address: '/home/shik9/Public/1/STDF-PyTorch-2 (copy)/out1/'

  criterion:
    type: PSNR
    unit: dB
